In [1]:
import subprocess

In [4]:

result = subprocess.check_output(['powershell', '-Command', 'Get-CimInstance Win32_Processor | Select-Object -ExpandProperty NumberOfCores']).decode().strip()
print("Physical cores:", result)

Physical cores: 4


In [5]:
import psutil
print("Physical cores:", psutil.cpu_count(logical=False))
print("Total cores:", psutil.cpu_count(logical=True))

Physical cores: 4
Total cores: 8


In [2]:
import psutil
import cpuinfo

# Logical cores
logical_cores = psutil.cpu_count(logical=True)
print(f"Logical cores: {logical_cores}")

# Total RAM
total_ram_bytes = psutil.virtual_memory().total
total_ram_gb = total_ram_bytes / (1024**3)
print(f"Total RAM: {total_ram_gb:.2f} GB ({total_ram_bytes:,} bytes)")

# CPU Cache information
cpu_info = cpuinfo.get_cpu_info()
print(f"\nCache Information:")
print(f"L1D Cache: {cpu_info.get('l1_data_cache_size', 'N/A')}")
print(f"L1I Cache: {cpu_info.get('l1_instruction_cache_size', 'N/A')}")
print(f"L2 Cache: {cpu_info.get('l2_cache_size', 'N/A')}")
print(f"L3 Cache: {cpu_info.get('l3_cache_size', 'N/A')}")

# Additional useful info
print(f"\nBrand: {cpu_info.get('brand_raw', 'N/A')}")
print(f"CPU Frequency: {psutil.cpu_freq().current:.2f} MHz")

Logical cores: 8
Total RAM: 15.84 GB (17,007,292,416 bytes)

Cache Information:
L1D Cache: N/A
L1I Cache: N/A
L2 Cache: 65536
L3 Cache: N/A

Brand: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
CPU Frequency: 2496.00 MHz


In [5]:

# CPU Model Information
print("\n" + "="*50)
print("CPU MODEL DETAILS")
print("="*50)

# Full brand name
print(f"Full CPU Model: {cpu_info.get('brand_raw', 'N/A')}")

# Extract individual parts if available
print(f"Vendor: {cpu_info.get('vendor_id_raw', 'N/A')}")
print(f"Architecture: {cpu_info.get('arch', 'N/A')}")
print(f"Bits: {cpu_info.get('bits', 'N/A')}")

# Windows-specific CPU info using WMI
import os
if os.name == 'nt':  # Windows
    import subprocess
    try:
        result = subprocess.check_output(
            ['wmic', 'cpu', 'get', 'Name,Manufacturer,MaxClockSpeed,NumberOfCores,NumberOfLogicalProcessors'],
            universal_newlines=True
        )
        print("\nDetailed CPU Info from WMI:")
        print(result)
    except Exception as e:
        print(f"WMI info unavailable: {e}")


CPU MODEL DETAILS
Full CPU Model: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
Vendor: GenuineIntel
Architecture: X86_64
Bits: 64
WMI info unavailable: [WinError 2] The system cannot find the file specified


In [6]:
import os
print("Total cores:", os.cpu_count())

Total cores: 8


In [23]:
import numpy as np
x = np.random.rand(1000000)
y = np.random.rand(1000000)


In [7]:
%timeit x*y

2.62 ms ± 178 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
%timeit x/y

2.96 ms ± 153 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
%timeit x+y

3.11 ms ± 208 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
%timeit x-y

3.12 ms ± 165 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [12]:
k = 0.2
%timeit x/k

2.76 ms ± 183 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [13]:
%timeit x*(1/k)

2.77 ms ± 65.7 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [20]:
import time

start = time.time()
result = x*y
end = time.time()
print(f"Time taken: {end - start:.6f} seconds")


Time taken: 0.003476 seconds


In [21]:
start = time.time()
result = x-y
end = time.time()
print(f"Time taken: {end - start:.6f} seconds")

Time taken: 0.002981 seconds


In [24]:
print(x*y)

[0.02802368 0.33066376 0.03623813 ... 0.26142914 0.3780423  0.40553173]


In [25]:
# Matrix slicing
X = np.random.rand(20,20)
print(X.shape)
X.flags

(20, 20)


  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [26]:
X_sliced = X[3:5,2:10]
print(X_sliced.shape)
X_sliced.flags

(2, 8)


  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [29]:
print(np.asfortranarray(X_sliced).shape)
np.asfortranarray(X_sliced).flags

(2, 8)


  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [30]:
print(np.ascontiguousarray(X_sliced).shape)
np.ascontiguousarray(X_sliced).flags

(2, 8)


  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [31]:
%timeit x = complex(8.1, 0.3)

91.1 ns ± 1.31 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [32]:
%timeit x = 8.1 + 1j*0.3

11.8 ns ± 0.144 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [33]:
a = np.arange(10)
b = np.arange(10)

In [34]:
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
